apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops

resources:
- ../../base

replicas:
- name: devops-app
  count: 1

images:
- name: devops-app
  newName: devops-app
  newTag: latest

patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: devops-app
  path: deployment-patch.yaml
